#! /usr/bin/env php

<?php

use Acme\NewCommand;
use GuzzleHttp\Client;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Laracasts Demo', '1.0');

// $app->add(new SayHelloCommand);
$app->add(new NewCommand(new Client()));

$app->run();