#! /usr/bin/env php

<?php
// run in terminal with './tasks <name of command> <arguments>'
use Acme\AddCommand;
use Acme\ShowCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Task App', '1.0');

try
{
	$pdo = new PDO('sqlite:db.sqlite');

	$pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
	$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
}
catch (Exception $exception)
{
	echo 'Could not connect to the database';
	exit(1);
}

$dbAdapter = new Acme\DatabaseAdapter($pdo);

$app->add(new ShowCommand($dbAdapter));
$app->add(new AddCommand($dbAdapter));

$app->run();